---
- name: Using the vars_prompt
  hosts: all
  tasks:
    - name: Perform the following {{ my_action }} on {{ my_package }}
      ansible.builtin.dnf:
        name: "{{ my_package }}"
        state: "{{ my_action }}"
      register: pkg_status
    - name: Display the information
      ansible.builtin.debug:
        msg: "This is {{ name }}"
...
